### ISSUE TITLE
Module should disclose its presence via System Report utility in CP

### ISSUE THREAD

**Issue by AugustMiller** [craftcms/cloud-extension-yii2#2]
Currently, Yii’s “bootstrapping” process bypasses mounting the module to the main app component, and therefore it isn't displayed in the **System Report** utility.

![Screen Shot 2023-06-28 at 09 42 10](https://github.com/craftcms/cloud-extension-yii2/assets/1895522/7aa50f29-a427-422d-9e54-856dd83b5145)

**Comment by kennethormandy** [comment]
Looks like this was fixed?

<img width="1058" alt="Screen Shot 2023-08-22 at 3 14 08 PM" src="https://github.com/craftcms/cloud-extension-yii2/assets/1581276/74efe0e3-a999-4538-87c7-2ab55e7b49f4">
