### ISSUE TITLE
[4.x]: Drag and drop upload should be disabled for custom sources

### ISSUE THREAD

**Issue by timkelty** [craftcms/cloud-extension-yii2#28]
### Description
The upload button is disabled, but the drag and drop is not.

### Craft CMS version

4.x and 5.x

### Installed plugins and versions

-

**Comment by i-just** [comment]
Hi Tim! I’m unable to replicate this. As per our chat, this might be related to the cloud extension, so I moved the issue here.

**Comment by timkelty** [comment]
https://linear.app/craftcms/issue/CLD-734/drag-and-drop-upload-should-be-disabled-for-custom-sources
