### ISSUE TITLE
Image dimensions not updated when replacing an image in the Craft Cloud file system

### ISSUE THREAD

**Issue by svale** [craftcms/cloud-extension-yii2#47]
### Description
In the CP Assets view, when using the "Replace file" option to replace an image assets with  another, it seems the image dimensions that are stored in the CDN URL are not replaced  / updated.  The new image, regardless of its original width/height, is displayed with the ratio of the first image. As far as I can tell, this is both backend and frontend (if cropping transformation is not applied). 

Locally on the local disc fallback of the file system, we see the expected behaviour (the new image retains its original format ratio).

### Steps to reproduce
1. Set up an assets volume using a Craft Cloud file system (NB: on a Craft cloud instance)
2. Upload an image (e.g. landscape mode)
3. Click the "Replace file" image menu option and replace with another image in a different format (e.g portrait)

### Additional info

- `craftcms/cms` version: 5.2.6
- `craftcms/cloud` version: 2.4.2
- PHP version: 8.2.20
- Database driver & version: SQL 8.0.32

- Plugins & versions: (**NB, NB**: aws-s3 is still installed, but no longer in use as we have migrated to craft cloud storage )
   "born05/craft-assetusage": "4.0.0",
    "craftcms/aws-s3": "2.2.1",
    "craftcms/ckeditor": "4.1.0",
    "craftcms/cloud": "*",
    "craftcms/cms": "5.2.6",
    "craftcms/feed-me": "6.2.0",
    "mmikkel/retcon": "3.2.0",
    "nystudio107/craft-closure": "^1.0",
    "nystudio107/craft-seomatic": "5.1.0",
    "nystudio107/craft-vite": "^5.0.0",
    "platformsh/config-reader": "^2.4",
    "putyourlightson/craft-sprig": "3.1.0",
    "spacecatninja/imager-x": "5.0.1",
    "spacecatninja/imager-x-craft-cloud-transformer": "^1.0.0-beta.1",
    "spicyweb/craft-embedded-assets": "5.1.0",
    "verbb/expanded-singles": "^3.0.0",
    "verbb/field-manager": "4.0.1",
    "verbb/formie": "3.0.0-beta.16",
    "verbb/hyper": "2.0.2",
    "verbb/many-to-many": "4.0.0",
    "vlucas/phpdotenv": "^5.4.0"

**Comment by timkelty** [comment]
Thanks for the report, @svale. We were able to reproduce the issue and are working on a fix now.

**Comment by timkelty** [comment]
@svale This is fixed in`craftcms/cloud` `1.61.0` and `2.6.0`. Thanks for the report!

**Comment by svale** [comment]
Brilliant - thanks!
